# -*- coding: utf-8 -*-
"""KMeans DBScan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XEDLeFLD1HyPOFaZQDTRxRfmXrAeLUCf
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, DBSCAN
from sklearn.datasets import make_moons

# Creating the two dimensional 'Moons' dataset
X,Y = make_moons(n_samples = 200, random_state = 100) # X = two dimensions, Y = label
print(X[:5,])

# Normalizing numerical features so that each feature has mean 0 and variance 1
feature_scaler = StandardScaler()
X_scaled = feature_scaler.fit_transform(X)

# Implementing K-Means CLustering
kmeans = KMeans(n_clusters = 2)
kmeans.fit(X_scaled)
plt.figure(figsize = (8,6))
plt.scatter(X[:,0], X[:,1], c=kmeans.labels_, cmap='plasma')
plt.xlabel('X1')
plt.ylabel('X2')
plt.show()

# Implementing DBSCAN
dbscan = DBSCAN(eps=0.10, min_samples=1)
#EPS is 
#The maximum distance between two samples for one to be considered as in the neighborhood of the other. 
#This is not a maximum bound on the distances of points within a cluster. 
#This is the most important DBSCAN parameter to choose appropriately for your data set and distance function.

#MIN SAMPLES IS 
#The number of samples (or total weight) in a neighborhood for a point to be considered as a core point. 
#This includes the point itself.
dbscan.fit(X_scaled)
plt.figure(figsize = (8,6))
plt.scatter(X[:,0], X[:,1], c=dbscan.labels_, cmap='plasma')
plt.xlabel('X1')
plt.ylabel('X2')
plt.show()

